# Generated by Django 6.0 on 2026-01-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.PositiveIntegerField(),
        ),
    ]
